# Generated by Django 5.2.7 on 2025-10-03 14:18

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('http_method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE'), ('HEAD', 'HEAD'), ('OPTIONS', 'OPTIONS'), ('TRACE', 'TRACE')], db_index=True, max_length=10)),
                ('path', models.CharField(max_length=500, validators=[django.core.validators.MinLengthValidator(1)])),
                ('query_string', models.TextField(blank=True, null=True)),
                ('remote_ip', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('response_status', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('response_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('request_size_bytes', models.PositiveIntegerField(blank=True, null=True)),
                ('response_size_bytes', models.PositiveIntegerField(blank=True, null=True)),
                ('is_authenticated', models.BooleanField(db_index=True, default=False)),
                ('is_staff', models.BooleanField(db_index=True, default=False)),
                ('is_superuser', models.BooleanField(db_index=True, default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Request Log',
                'verbose_name_plural': 'Request Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp', 'http_method'], name='audit_reque_timesta_44fbba_idx'), models.Index(fields=['user', 'timestamp'], name='audit_reque_user_id_0634d8_idx'), models.Index(fields=['remote_ip', 'timestamp'], name='audit_reque_remote__8109e0_idx'), models.Index(fields=['response_status', 'timestamp'], name='audit_reque_respons_0e1670_idx'), models.Index(fields=['path', 'timestamp'], name='audit_reque_path_260cdb_idx')],
            },
        ),
    ]
